{% set version = "0.36.0" %}

package:
  name: wheel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wheel/wheel-{{ version }}.tar.gz
  sha256: e17f05e14282d0e666327f800ef43123b40f3dbc13a86193b604f2ebfae0dabc

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - wheel = wheel.cli:main

requirements:
  host:
    - python
    - setuptools >=40.9
  run:
    - python

test:
  imports:
    - wheel
  commands:
    - wheel --help

about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - mingwandroid
