{% set version = "0.35.0" %}

package:
  name: wheel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wheel/wheel-{{ version }}.tar.gz
  sha256: 625e645aae0706ad09690bded523196a065fbcf9afcdb2d713b59e01ef8699c0

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - wheel = wheel.cli:main

requirements:
  host:
    - python
    - setuptools >=42
    - setuptools_scm >=3.4
    - toml
  run:
    - python
    - packaging >=20.2

test:
  imports:
    - wheel
  commands:
    - wheel --help

about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - mingwandroid
