{% set name = "wheel" %}
{% set version = "0.41.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55a0f0a5a84869bce5ba775abfd9c462e3a6b1b7b7ec69d72c0b83d673a5114d

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -c "import flit_core.buildapi; flit_core.buildapi.build_wheel('.')" && {{ PYTHON }} -m installer --no-compile-bytecode wheel-*.whl
  entry_points:
    - wheel = wheel.cli:main

requirements:
  host:
    - python
    - flit-core >=3.8,<4
    - python-installer
  run:
    - python

test:
  imports:
    - wheel
    - wheel.cli
    - wheel.vendored
    - wheel.vendored.packaging
  requires:
    - pip
  commands:
    - pip check
    - wheel --help
    - wheel version

about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
  description: |
    This library is the reference implementation of the Python wheel packaging standard, 
    as defined in PEP 427.
    It has two different roles:
      1. A setuptools extension for building wheels that provides the bdist_wheel setuptools command
      2. A command line tool for working with wheel files
  dev_url: https://github.com/pypa/wheel
  doc_url: https://wheel.readthedocs.io/

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - mingwandroid
  skip-lints:
    - missing_wheel
