travis:
  secure:
    BINSTAR_TOKEN: GHYcE/52eTRsLBYsJDAOSZkKHqIvdCYDTsBK86s9U2F2OQYJ/ZJTJNJSnGyc/Y3YgU+Vx7sJd0BvX3qKT0gTlVuQDqyQCQCiFx1FiD4fe8bSlRYtoN2tF92yO+caDLthQBTImkB8bwq9US9yMKZGSuKfUMPgpEkT6kjW/qHihGuuJVnyjSvrn3KNCVtkC0MHQEfiJYBvd9jkIHq/j9Cw36FqPkSiPpLTCzgvaw39E+VvU5Isomoc552I3l+GEF4wZnXLwcM2kpfmLCU8gmuFWrVk5v/+T/I6edPix2OKLgOoe0CvXsF0C+iuU32vxv68FWK65F3EYjQNvB0oaNthcT88TwcJ0sV2v54kHXi4BIw8TgLWWpm9Ocv+kf/YQ1o0txpVCPWpKhYEXfgNutDOLNfrG6+D5VBktTtPAf3+lLn6gXKDuxYKm0hOrPtr/5PYgvA1amadRSZUSX4aRlHieTyGhOb3GZ8iAqqnK6oS1c+9wEF9QVSZI7dibiCUmZnLGhMqZBr0zC3q8WsgiETLdoveTZVDW7QvpNm536QfBtybQbPvC1m0eEozxtNzNLBq+8LMdvhXI7DniAR+9GJEWaQfkiKXAKHBweGTCTAXMe4XYtNVTCJuL5g8LkJNEHVIhQCCSvr2h8ICSmMR+hTU4mcYUWSAQK6r5hpsN/jTph0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
